const data = {
  products: [
    {
      name: 'Buncis',
      slug: 'buncis',
      category: 'sayur',
      image: '/images/buncis.jpg',
      price: 10,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Sayur segar dan bagus',
    },
    {
      name: 'Kacang Panjang',
      slug: 'kacang-panjang',
      category: 'sayur',
      image: '/images/kacangpanjang.jpg',
      price: 5,
      rating: 4.1,
      numReviews: 5,
      countInStock: 20,
      description: 'Sayur segar dan bagus',
    },
    {
      name: 'Pakcoy',
      slug: 'pakcoy',
      category: 'sayur',
      image: '/images/pakcoy.jpg',
      price: 2,
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'Sayur segar dan bagus',
    },
    {
      name: 'Sawi',
      slug: 'sawi',
      category: 'sayur',
      image: '/images/sawi.jpg',
      price: 3,
      rating: 4.6,
      numReviews: 7,
      countInStock: 20,
      description: 'Sayur segar dan bagus',
    },
    {
      name: 'Terong Ungu',
      slug: 'terong-ungu',
      category: 'sayur',
      image: '/images/terongungu.jpg',
      price: 5,
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'Sayur segar dan bagus',
    },
    {
      name: 'Apel',
      slug: 'apel',
      category: 'buah',
      image: '/images/apel.jpg',
      price: 3,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Buah Segar dan bagus',
    },
    {
      name: 'Jeruk',
      slug: 'jeruk',
      category: 'buah',
      image: '/images/jeruk.jpg',
      price: 2,
      rating: 4.2,
      numReviews: 8,
      countInStock: 20,
      description: 'Buah Segar dan bagus',
    },
    {
      name: 'Pepaya',
      slug: 'pepaya',
      category: 'buah',
      image: '/images/pepaya.jpg',
      price: 4,
      rating: 4.1,
      numReviews: 8,
      countInStock: 20,
      description: 'Buah Segar dan bagus',
    },
  ],
};

export default data;
